# Generated by Django 4.2.7 on 2024-06-04 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather_api', '0003_weather_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='weather',
            name='temperature',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
