# Generated by Django 5.0.6 on 2024-06-05 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather_api', '0005_weather_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weather',
            name='description',
        ),
    ]
