# Generated by Django 5.0.6 on 2024-06-05 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather_api', '0006_remove_weather_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='weather',
            name='description',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
