# Generated by Django 5.0.6 on 2024-06-05 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather_api', '0007_weather_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='weather',
            name='wind',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
